[vision]
provider = "ollama"
retries = 3
timeout = 10

[vision.providers.openai]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = { type = "env", name = "OPENAI_API_KEY" }

[vision.providers.ollama]
model = "gemma3"
base_url = "http://localhost:11434/v1"
api_key = { type = "inline", key = "dummy-key" }

[vision.providers.openrouter]
model = "meta-llama/llama-3.2-11b-vision-instruct:free"
base_url = "https://openrouter.ai/api/v1"
api_key = { type = "env", name = "OPENROUTER_API_KEY" }

[filtration]
chart_labels = ["picture", "figure", "chart", "diagram"]

[processing]
ocr_lang = "eng"
zoom_factor = 2
